//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicaciones
    {
        public int IdPublicacion { get; set; }
        public string NombrePublicacion { get; set; }
        public string DescripcionPublicacion { get; set; }
        public string ImgPublicacion { get; set; }
        public Nullable<bool> Visible { get; set; }
    }
}
